backend:
  name: git-gateway
  branch: main 
  
media_folder: "public/images"
public_folder: "images"
 
collections: 
 - name: "blog"
   label: "Blog"
   folder: "content"
   create: true
   fields:
    - { label: "Title", name: "title", widget: "string" }
    - { label: "Description", name: "description", widget: "string" }
    - { label: "Author", name: "author", widget: "string" }
    - { label: "Published", name: "published", widget: "string" }
    - { label: "Featured Image", name: "image", widget: "image" }
    - { label: "Body", name: "body", widget: "markdown" }
